version: '3.8'

services:
  frontend_api:
    build: ./frontend_api
    ports:
      - "8000:8000"
    depends_on:
      - frontend_db
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend_db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frontend_db
    ports:
      - "5432:5432"
    volumes:
      - frontend_db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_db_data:

